### ISSUE TITLE
Xcode screen shots are blurry

### ISSUE THREAD

**Issue by markd2** [secondgear/Achieving-Zen-With-Auto-Layout#10]
Hi!  Loving the book.  There are some xcode screen shots, and they're really blurry.  Two examples attached - one from iAnnotate PDF reader on an ipad, and the other is preview. Other illustrations are nice and crisp.

<img width="1238" alt="screen shot 2016-02-15 at 10 17 19 am" src="https://cloud.githubusercontent.com/assets/609957/13052544/7df5f50e-d3cd-11e5-9ff5-e1fb5244ca52.png">

![img_1191](https://cloud.githubusercontent.com/assets/609957/13052556/958ecd4e-d3cd-11e5-9c9a-d7f7d341fd6b.PNG)

**Comment by justin** [comment]
Downscaling FTL. I am trying to find a way to handle those better. They need to be capped at 500px wide, but Photoshop is doing a pretty crummy job doing the scale.

**Comment by justin** [comment]
OK, I think I have these looking a little less blurry. I'll generate a new build soon (once I get through your other tickets)
