### ISSUE TITLE
Minor code formatting nits

### ISSUE THREAD

**Issue by markd2** [secondgear/Achieving-Zen-With-Auto-Layout#17]
minor, minor nits. But that's what programmers obsess about, right? :-)

page 7
<img width="285" alt="screen shot 2016-02-15 at 5 18 07 pm" src="https://cloud.githubusercontent.com/assets/609957/13061779/1e8f7be0-d408-11e5-876f-45182a74a594.png">

page 58
<img width="390" alt="screen shot 2016-02-15 at 5 17 46 pm" src="https://cloud.githubusercontent.com/assets/609957/13061772/0f09f57e-d408-11e5-9bfc-541af922c6fd.png">

page 59 

(ditto for the continuation of this code onto the next page)
(ditto for the same kind of code on 61)

<img width="178" alt="screen shot 2016-02-15 at 5 23 12 pm" src="https://cloud.githubusercontent.com/assets/609957/13061916/e3bfd9be-d408-11e5-82c8-016a8c2ee4f8.png">

page 67

<img width="577" alt="screen shot 2016-02-15 at 6 34 08 pm" src="https://cloud.githubusercontent.com/assets/609957/13063115/c69948c0-d412-11e5-91cd-5b03b7c0fd9d.png">

page 79

<img width="289" alt="screen shot 2016-02-18 at 9 01 32 pm" src="https://cloud.githubusercontent.com/assets/609957/13164401/e17f6a80-d682-11e5-80ef-554c0c580b45.png">

pg 89

<img width="414" alt="screen shot 2016-02-20 at 7 38 37 pm" src="https://cloud.githubusercontent.com/assets/609957/13200136/9cdb123e-d809-11e5-97a5-dc59d48bca82.png">

pg 91

<img width="495" alt="screen shot 2016-02-20 at 7 53 53 pm" src="https://cloud.githubusercontent.com/assets/609957/13200186/bfd64c84-d80b-11e5-8472-27622fda1d71.png">

**Comment by justin** [comment]
Thank you! This is where a second set of eyes help. I just went through and scrubbed all these so they should be more uniform in the next PDF.
