### ISSUE TITLE
Chapter 4 - The Auto Layout Process - Laying Out Views section 

### ISSUE THREAD

**Issue by RndPrecision** [secondgear/Achieving-Zen-With-Auto-Layout#7]
Written:
“First, you can call setNeedsLayout(), which will notify the system that you want to do a layout pass and will do it when convenient.”

Missing "it" (or other word): 
“... pass and it will do it when convenient.”

**Comment by justin** [comment]
Thanks. I adjusted the sentence to be a bit more clear in the lab.
