### ISSUE TITLE
Chapter 05 - Our First Auto Layout Example

### ISSUE THREAD

**Issue by RndPrecision** [secondgear/Achieving-Zen-With-Auto-Layout#8]
Written:
“Next, let’s add the an edge constraint to explicitly set 20pts of padding from the top of the parent view from the top of the image view.”

Probably should be written:
“Next, let’s add an edge constraint to explicitly set 20pts of padding from the top of the parent view from the top of the image view.” (drop "the" after "add")

**Comment by justin** [comment]
Fixed. Thanks.
